### ISSUE TITLE
#region/#endregion is working only when not indented

### ISSUE THREAD

**Issue by kine** [BartPermentier/al-toolbox#1]
![image](https://user-images.githubusercontent.com/110221/54422847-a2079c00-470f-11e9-82f5-78d50a3ff533.png)
![image](https://user-images.githubusercontent.com/110221/54422937-d7ac8500-470f-11e9-82e4-9e63e3dd88a3.png)
![image](https://user-images.githubusercontent.com/110221/54422951-df6c2980-470f-11e9-8deb-3e29ae2beced.png)

The extension is not working correctly on my install. When the lines are indented, no possibility to collapse at all. When not indented, on both (begin and end) I have possibility to collapse and it is collapsed to two lines instead one. And of course, autoformat will indent them...

I do not know if it is problem in your extension or in VSCode at all...

**Comment by BartPermentier** [comment]
Hello Kine, sorry for the late reply. I am unable to reproduce your issue.
What version of AL Language are you using? And what version of VSCode? The BC AL Language will automatically indent the regions with the rest of the code when you save.
Maybe send me a screenshot of all the extensions you are using?

**Comment by kine** [comment]
Version: 1.32.2 (user setup)
Commit: e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951
Date: 2019-03-13T02:00:46.035Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

AL Language 2.1.100503
AL Code Outline 0.0.13
AL Language Tools 0.0.22
AL Object Designer 0.0.5
AL Variable Helper 2.3.1
ALRunner 3.2.1
CRS AL Language Extension 1.0.15
NaverticAL 0.2.0

and many other regarding powershell, XML, Json, YAML, TS, SQL, REST etc. (around 42 extensions)

And yes, saving will format the file and thus it stop work... :-)

The AL Language have some default functionality regarding this (functions, groups etc.). May be conflict?
