### ISSUE TITLE
Label locked parameter

### ISSUE THREAD

**Issue by weha** [BartPermentier/al-toolbox#109]
Please provide support for Locked parameter after a Label.
Currently it complains that it is the incorrect translation format.
![image](https://github.com/BartPermentier/al-toolbox/assets/5836955/13963b68-096a-4118-95fd-34f3c6c2f13e)

**Comment by dsaveyn** [comment]
Hi,

Could you provide us with some more context since this appears to be working in the latest version:

![image](https://github.com/BartPermentier/al-toolbox/assets/92365904/e8df76bf-666e-4f43-999a-0a651e1d100f)

(I've added the second line to demonstrate the functionality is working)

**Comment by dsaveyn** [comment]
@weha Closing this for now since no feedback was received.
