### ISSUE TITLE
Feature Request: Change Source Folder

### ISSUE THREAD

**Issue by metda11** [BartPermentier/al-toolbox#121]
Hi BartPermentier,
thanks for your great solution!
Is there a chance that you add the option to change the source Folder please!
e.g. from src to AL
That would be great!

Thanks in advance!

Greetings
Daniel

![image](https://github.com/BartPermentier/al-toolbox/assets/73653971/5301b680-a475-4af8-be74-f677741ff05e)

**Comment by fvet** [comment]
@dsaveyn Can you review this request pls?

**Comment by dsaveyn** [comment]
@metda11 My apologies for the late reply. We can add such a parameter for sure:) I'll keep you updated.

**Comment by metda11** [comment]
Thanks, looking forward to have this feature. Until yet it´s not released...
Greetings
