### ISSUE TITLE
Please support AL Language 6.0.x

### ISSUE THREAD

**Issue by NKarolak** [BartPermentier/al-toolbox#17]
When using the AL Language version 6.0.x (BC 17), regions as a means to fold/unfold are not supported.
Could you please add that support?

**Comment by BartPermentier** [comment]
Okay we will look for a solution asap!

**Comment by BartPermentier** [comment]
The Extension is being uploaded now. Your VSCode should download the new version within the hour.

**Comment by NKarolak** [comment]
Successfully tested. Thanks a lot!

**Comment by BartPermentier** [comment]
Hey, we just discovered that in some cases it would prevent you from collapsing other parts. If this is a big issue you can always fallback to the previous version while we work on a fix.
![image](https://user-images.githubusercontent.com/24684493/92125047-cfae3c80-edfe-11ea-84e9-47eac100fba2.png)

**Comment by NKarolak** [comment]
Thank you for informing me. However, so far, I've not encountered that case yet :)
