### ISSUE TITLE
AL Toobox prevents folding icons in .al files with many lines

### ISSUE THREAD

**Issue by lvanvugt** [BartPermentier/al-toolbox#23]
@BartPermentier, today we found out that when AL Toolbox is enabled in VSCode [folding icons](https://code.visualstudio.com/docs/editor/codebasics#_folding) disappear. And any shortcut key combination to fold certain part does also not work any more.

See also my tweet thread: https://twitter.com/lucvanvugt/status/1316723666256883712

**Comment by BartPermentier** [comment]
Hey Luc,
We will look into it. Can you make sure that you have the latest version installed of ALTB please? Version 2+ should have already resolved this. Or is it blocking another language?

**Comment by lvanvugt** [comment]
Version 2.0.2 installed

![image](https://user-images.githubusercontent.com/18466198/96211061-9dead280-0f73-11eb-957c-0bb4b67ca5b1.png)

And this is all installed next to AL Toolbox

![image](https://user-images.githubusercontent.com/18466198/96211161-db4f6000-0f73-11eb-9af9-3f4b9d9ecd05.png)

**Comment by KasperDeSmedt** [comment]
@lvanvugt This should be fixt in the next version. For the moment you can disable the folding provided by this extension by setting  ALTB.DisableCustomFolding to true in your user settings. This does mean that folding for regions with marker '//#(end)region' won't work.

**Comment by BartPermentier** [comment]
The next version is published and should be available within the hour.

**Comment by NKarolak** [comment]
For me, in v2.0.3 it is working again :-)

**Comment by lvanvugt** [comment]
#me2
