### ISSUE TITLE
Intellisense no longer finds AL specific Values when start writing with uppercase

### ISSUE THREAD

**Issue by BernhardKloibmueller** [BartPermentier/al-toolbox#25]
Hallo,

I discovered that the intellisenxe of the AL Language Extension is disrupted with the AL Toolbox enabled.

When I start writing a new word for excample "rec" VS Code only suggests templates and not "Record". I would have to write "Rec" to get "Record" suggested. This works for all values.

rec:
![grafik](https://user-images.githubusercontent.com/46522333/97572490-9c47f280-19e8-11eb-86c0-7945231435a3.png)

Rec:
![grafik](https://user-images.githubusercontent.com/46522333/97572495-a1a53d00-19e8-11eb-81bd-55987c8311be.png)

I started this on the AL Extension and got the hint, that it works without other apps installed and so I found the AL Toolbox as problem: https://github.com/microsoft/AL/issues/6264.

Best Regards
Bernhard

**Comment by BartPermentier** [comment]
Hey,

We will have a look at it asap. For now can you use the setting in
altoolbox to disable the snippets of the extension please?

**Comment by KasperDeSmedt** [comment]
@BernhardKloibmueller 
This should be fixed in the next version (2.0.4). The next version is published and should be available within the hour.
Let us know if this fixes your issue 🙂

**Comment by BernhardKloibmueller** [comment]
@KasperDeSmedt 

Thank your for your fast responce and fix. 
It is now working with lowercase characters again.
