### ISSUE TITLE
Fipa Snippet

### ISSUE THREAD

**Issue by Joriek** [BartPermentier/al-toolbox#3]
Hi,

Can you modify the FIPA snippet so we don't have to remove the "FieldName" text for IntelliSence to work?

![image](https://user-images.githubusercontent.com/6583705/56273202-92a7b400-60fc-11e9-9b26-7af80ae90329.png)

![image](https://user-images.githubusercontent.com/6583705/56273206-94717780-60fc-11e9-828f-ca60cf9e0608.png)

Thanks!

**Comment by BartPermentier** [comment]
done
