### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by jmadrigalTCN** [BartPermentier/al-toolbox#31]
Great extension. Especially renumbering tool. Great to convert an AL Extension from OnPremise to SaaS or viceversa

It would be great if you renumbered the fields in table extensions to.

**Comment by BartPermentier** [comment]
Thanks, we will probably add it before the end of the year :)

**Comment by jmadrigalTCN** [comment]
Thank you ever so much.


Un saludo.

[cid:image002.png@01D55F38.9CB60700]<http://www.tecon.es/>

José Joaquín Madrigal Couque       Coordinador BC

jmadrigal@tecon.es

967 505 024       www.tecon.es<http://www.tecon.es/>

[cid:image003.png@01D55F38.9CB60700]<http://www.grupotecon.com/>




________________________________
De: Bart Permentier <notifications@github.com>
Enviado: lunes, 14 de diciembre de 2020 17:05
Para: BartPermentier/al-toolbox <al-toolbox@noreply.github.com>
Cc: JOSE JOAQUIN MADRIGAL COUQUE <jmadrigal@tecon.es>; Author <author@noreply.github.com>
Asunto: Re: [BartPermentier/al-toolbox] Improvements (#31)


Thanks, we will probably add it before the end of the year :)

**Comment by BartPermentier** [comment]
#32 Related

**Comment by BartPermentier** [comment]
The new version has been published. Please close this if it works :)
Sorry it was kind of busy at year end.
