### ISSUE TITLE
Renumber fields

### ISSUE THREAD

**Issue by StefanMaron** [BartPermentier/al-toolbox#32]
Would it be possible to also renumber fields in the current table/all objects ?
This should maybe not happen wenn doing a normal renumber objects, because sometimes an automatic renumber of fields can break stuff with transferfields.
But if I do not depend on this or if I want to renumber fields in selected objects this would be very usefull!

**Comment by BartPermentier** [comment]
#31 related.
We will create a new action to renumber fields of current object / all objects and it will ask you the starting number

**Comment by BartPermentier** [comment]
The new version has been published. Please close this if it works :)
