### ISSUE TITLE
EnumExtensions are not getting renumbered via "Renumber AL objects"

### ISSUE THREAD

**Issue by dannoe** [BartPermentier/al-toolbox#38]

**Comment by BartPermentier** [comment]
Thanks for reporting the bug, we will look into it.
But don't expect them anytime soon since we have a lot of work at the moment. I will let you know once they are live.

**Comment by BartPermentier** [comment]
Update is published now, please close this Issue if it is resolved.
Thanks!

**Comment by dannoe** [comment]
I am not quite sure if this is a problem on my side, but I can not use any command from the al-toolbox extension anymore.
Everytime I try to run an action:

![grafik](https://user-images.githubusercontent.com/7450586/123102507-a78ed900-d424-11eb-910b-689b2517eff1.png)
Even for other commands:
![grafik](https://user-images.githubusercontent.com/7450586/123102634-cd1be280-d424-11eb-88dd-19e52f2d2b31.png)


I already reinstalled the extension and disabled all others but still nothing.

**Comment by dannoe** [comment]
It works now with v2.0.12 👍🏼
