### ISSUE TITLE
Duplicate fields in ALTB: Generate SetLoadFields: 

### ISSUE THREAD

**Issue by ti-jalopez** [BartPermentier/al-toolbox#39]
Hi,

When I use "ALTB: Generate SetLoadFields" to create / add setloadfields, if one field doesn't exists in current fields list, and this field is used more than one time, the same field is added to SetAddLoadFields as many times as it is used.

```
myRec.SetLoadFields("Cost Center Code","Cost Type No.", "Cost Center Code");  //Created by ALTB: Generate SetLoadFields
...
myRec.FindSet(false);
repeat
  myVar1 := myRec."Cost Center Code";
  myVar2 := myRec."Cost Type No.";
  myVar3 := myRec. "Cost Center Code";
  ...
until myRec.Next = 0;

```
Best regards,

**Comment by BartPermentier** [comment]
Hey,

thanks for reporting the bug, we will look into it!
But don't expect them anytime soon since we have a lot of work at the moment. I will let you know once they are live.

**Comment by ti-jalopez** [comment]
Hi,

I've been researching the problem, and I discover ho to fix it:

In function addOrModifySetLoadFieldsToEdit: https://github.com/BartPermentier/al-toolbox/blob/21e2fc7e9913dddeb31d0a2ddc38117ed8d33b78/src/codeGeneration/setLoadFields/setLoadFields.js#L159
The parameter fields sometimes contains duplicate field names. I've tested to remove duplicate values from fields, and that solve the issue.
I've done next modification marked as "JAL:001" in local code on installed extension, and it runs fine:

```
//Local file: %USERPROFILE%\.vscode\extensions\bartpermentier.al-toolbox-2.0.9\src\codeGeneration\setLoadFields.js
function addOrModifySetLoadFieldsToEdit(edit, position, fields, document, loadFieldsInfo, recName) {
    if (fields.length === 0) return 0;
    const line = document.lineAt(position.line);
    const indent = line.text.substr(0, line.firstNonWhitespaceCharacterIndex);
//--JAL:001
//Clear duplicate fields
var originFields  = fields
var fields = fields.filter((v, i, a) => a.indexOf(v) === i);
// vscode.window.showInformationMessage(`JAL TEST addOrModifySetLoadFieldsToEdit=${fields}`);
//++JAL:001    
    if (loadFieldsInfo) {
        fields = fields.filter(field => !loadFieldsInfo.existingFields.includes(field));
        if (fields.length === 0) return 0;
        edit.insert(
            loadFieldsInfo.endPosition,
            `${loadFieldsInfo.existingFields.length === 0 ? '' : ', '}${fields.join(', ')}`);
    } else
        edit.insert(
            line.range.start,
            `${indent}${recName}.SetLoadFields(${fields.join(', ')});\n`
        );
    return fields.length;
}

```
Can you aply this changes in your extension and publish a new version?

Best regards,

José Antonio López

**Comment by Joriek** [comment]
Hello José, thank you for your code snippet.
One of our colleagues has resolved this issue, you can find the pull request [here](https://github.com/BartPermentier/al-toolbox/pull/41).

Bart will publish this new version of the extension as soon as possible.

Best regards
Joriek Rogge

**Comment by BartPermentier** [comment]
Update is published now, please close this Issue if it is resolved.
Thanks!

**Comment by ti-jalopez** [comment]
There is an error when I try to use ALTB: Generate SetLoadFields. Also occurs with other ALTB commands !!
![image](https://user-images.githubusercontent.com/68008246/123099352-66052a80-d432-11eb-9566-fed2f50b15ed.png)

I've tested to reload VSCode after upgrade extension, exit from VSCode an open, uninstall and install extension, but somethink is wrong, the commands of the extensions fails to lauch.

**Comment by BartPermentier** [comment]
Hey,

thanks for reporting a fix has been published and should be available soon. Version 2.0.12 should be fine.
Just fyi apparently our compiler of the vsix needed an update, so no bug in the code but our compiler mismatch with a newer version of Visual Studio Code.

Don't forget if you still have issues just revert back to a previous version of the app so you can continue working while we fix it.

**Comment by ti-jalopez** [comment]
@BartPermentier,
I've tested version 2.0.12 and it runs fine.
You can close this issue.
Tanks!!
