### ISSUE TITLE
Multiple level regions

### ISSUE THREAD

**Issue by stefanoPrimo** [BartPermentier/al-toolbox#4]
Hi,
it will be very helpful if the regions could be multi-levels like this:
 
```
//#region Level1
     //#region Level2

     //#endregion Level2
//#endregion Level1
```

Let me know if it is possible
Stefano

**Comment by BartPermentier** [comment]
Hey,

I looked into it but didn't find a way to achieve this. But my scripting skills are very limited since I'm just an AL developer...
Anyone is welcome to contribute if you find someone with more experience to achieve this :)
Sorry I can't help you!

**Comment by NKarolak** [comment]
This feature is working for me, so probably this issue could be closed?

**Comment by stefanoPrimo** [comment]
I'm sorry but I don't think so.
The missing feature I think is the indentation, with this it could be a lot better

**Comment by NKarolak** [comment]
Ah, then I clearly misunderstood, sorry!

**Comment by stefanoPrimo** [comment]
No worries, it was a bit cryptic as a GitHub issue!

**Comment by BartPermentier** [comment]
We decided not to do this change since Microsoft now also uses Regions and we don't want to put more stress on the AL formatter. You could use https://marketplace.visualstudio.com/items?itemName=mihelcic.colored-regions
to give different colors to your regions.
Hope it helps :)
