### ISSUE TITLE
Prefix Objects adds too many double quotes

### ISSUE THREAD

**Issue by markbrummel** [BartPermentier/al-toolbox#44]
When prefixing "unprefixed" objects that have a space in the name, it adds too many Double Quotes

"My Codeunit"
becomes

"PTE""My Codeunit"""

**Comment by BartPermentier** [comment]
Hey Mark,

I'm sorry it's a known "bug" it only replaces prefixes it does not add them. I believe the CRS Extension adds prefixes.

**Comment by markbrummel** [comment]
No, the CRS does not do a proper "Rename". I tested it, and it is also explicitly mentioned in the documentation. Is it a lot of work for you to fix it? It would be golden for a lot of partners who forgot it before they moved from C/Side to AL.

**Comment by BartPermentier** [comment]
Hey,

I assigned a dev on this but this is obviously not our highest priority.

**Comment by markbrummel** [comment]
I think that you're going to make lots of people happy with this. If it is in, I'll write a blog post about it. Thanks on behalf ot the people who need this.

**Comment by BartPermentier** [comment]
Hey,

@Krisje1973 did the requested change and it is currently live. Please close this if it works. Thanks!

**Comment by BartPermentier** [comment]
Seems to be working so closing this.
