### ISSUE TITLE
ALTB Snippets always show up in suggestions

### ISSUE THREAD

**Issue by rvanbekkum** [BartPermentier/al-toolbox#5]
Hi @BartPermentier,

When writing code in an AL file and using Ctrl+Space to get suggestions, I always get the ALTB snippets first even when they are not appropriate at the place.
See the following example:
![withextension](https://user-images.githubusercontent.com/7383241/60246561-352fa080-98bf-11e9-8ecc-95a05003448a.png)
vs.
![original](https://user-images.githubusercontent.com/7383241/60246768-b38c4280-98bf-11e9-85a2-a2113e17cac4.png)

Is it possible to make a change so that these snippets become 'context-aware' so that they do not always show up?

**Comment by BartPermentier** [comment]
Hey,

very strange; I will have a look at this as soon as I'm able.

**Comment by NKarolak** [comment]
It would be wonderful to get it solved ;-)

**Comment by BartPermentier** [comment]
Hey,

As of today you can now disable our snippets in the settings of AL Toolbox.
In the future we are looking on making it more context aware.

@waldo1001 I believe the "Control Snippets" extension will no longer be able to disable the snippets from AL Toolbox so here to let you know to use the setting instead :)

**Comment by waldo1001** [comment]
I'm going to check out how you did that ;-)

**Comment by NKarolak** [comment]
Workaround: https://twitter.com/KarolakNatalie/status/1321808003578896385?s=20

**Comment by BartPermentier** [comment]
This seems to be working as expected so closing the issue.
