### ISSUE TITLE
Bug: copy fields to related tables

### ISSUE THREAD

**Issue by TimCsr** [BartPermentier/al-toolbox#60]
When I use "copy fields to related tables" on the customer table, all fields must be transferred to the vendor and contact table. I have a custom table that also contains "Contact" ("GLT Contact Industry - Contact"). Fields are copied to this table as well, this should not be the case.
![image](https://user-images.githubusercontent.com/50943286/140510169-23cd54fc-4ab0-4743-8c6e-b998bde5a1d1.png)
![image](https://user-images.githubusercontent.com/50943286/140510256-432bf9c2-5113-40f8-b7ba-b4e8e764a01d.png)

**Comment by dsaveyn** [comment]
Hi,

Thank you for reporting this issue. Our apologies for the delay. The fix will be included in the next release.
