### ISSUE TITLE
Renumber Objects - permissionset Object

### ISSUE THREAD

**Issue by pri-kise** [BartPermentier/al-toolbox#64]
The permissionset Object isn't renumbered. I guess this is missing somehow in the renumbering process.
Maybe permissionset extenions are missing, too?

**Comment by BartPermentier** [comment]
Yes, these are new object types that we did not foresee. Added to the backlog.

**Comment by maartenbiesbrouck** [comment]
It does the job, only the reportextension and permissionset is not automatically update.
