### ISSUE TITLE
ALTB Region snippets conflict with AL Object ID Ninja

### ISSUE THREAD

**Issue by fvet** [BartPermentier/al-toolbox#65]
@dsaveyn @BartPermentier 
When i type `table` followed by IntelliSense (`Ctrl+Space`), all snippets are properly proposed. (OK)

![image](https://user-images.githubusercontent.com/25268332/149943780-33dfbbd8-8852-4577-965f-1f0d3b293e42.png)

However, when I continue and add a **`space`**, the region snippets from AL Toolbox are still listed / proposed, although to me it makes no more sense, since 'table' is no longer the active context. (NOK)

![image](https://user-images.githubusercontent.com/25268332/149943805-7fae9bf3-6f35-45ef-8f49-aa938197c355.png)

I need to hit `escape`, to access the correct IntelliSense (`Ctrl+Space`) is was looking for (the one proposing an Object ID). In short, the ALTB snippets conflicts with a proper use of AL Object ID Ninja.

![image](https://user-images.githubusercontent.com/25268332/149943835-c10f9949-b4af-4b2f-9fee-235632e7284f.png)

What's the value of **including the space** as part of the expression to propose the ALTB region snippets? 

_Additionally, maybe a setting could be added to disable the region snippets?_

**Comment by BartPermentier** [comment]
Hey @fvet,
Add the following setting to your user settings.json
`"editor.snippetSuggestions": "bottom",`
If this doesn't help you can also add:
`"editor.suggest.snippetsPreventQuickSuggestions": true,`
And if that still is not enough you can disable those snippets in the ALTB Settings
![image](https://user-images.githubusercontent.com/24684493/150093349-899b1d9d-0281-4e8e-bc94-367afbf05279.png)

We use the snippet from Waldo to create tables: ttable.
When id is selected you press delete and then hit Ctrl + Space for IntelliSense
![image](https://user-images.githubusercontent.com/24684493/150093806-0cc0c921-8f50-40c7-8b6f-033d52a1d3a7.png)

Hope this helps!
