### ISSUE TITLE
Revise snippets / AL Language Tools support ?

### ISSUE THREAD

**Issue by fvet** [BartPermentier/al-toolbox#66]
AL Toolbox closely integrates with 'AL Language Tools' for some of the **"r... (ALTB)"** snippets. Looking into the release notes / open issues from 'AL Language Tools', seems like the extensions is no longer actively maintained... (Also see https://github.com/LauraNicolas/al-language-tools/issues/30#issuecomment-1025775971) 

It would be nice if the ALToolbox **snippets** (those containing a fix **NLB** value) could be updated, to support another comment structure (regex) that is used by other extensions, such as [Xliff Sync](https://robvanbekkum.nl/xliff-sync-overview/), which uses a slightly different syntax to manage translations via code:  

`nl-BE=value` instead of `NLB="Value"`

Additionally, `ALTB.CheckCommentTranslations` should also respect the new / custom regex format.

![image](https://user-images.githubusercontent.com/25268332/151812779-6c51fd1a-894c-4772-911a-f368abf668a5.png)

----

Alternatively, we could opt to no longer using the ALTB snippets and use the native Xliff-Sync snippets instead.

![image](https://user-images.githubusercontent.com/25268332/151813838-61c0a276-7835-4379-b0c7-2c35519ed55a.png)

**Comment by BartPermentier** [comment]
Thanks, I didn't know that :) Let's discuss next week!

**Comment by fvet** [comment]
Can we please have a new setting `ALToolbox.useISOCodeInLanguageSnippets` (at least support on folder level)?

- When disabled (default value), the `rNLB`, `rFRB `snippets would still insert `NLB `and `FRB `tags for the comments / translations.
- When enabled the `rNLB`, `rFRB `snippets should insert the ISO codes `nl-be` and `fr-be` tags for the comments / translations.

**Comment by dsaveyn** [comment]
As discussed, two new settings (Snippet Target Language & Snippet Target Language 2) were added. The default values are set to NLB/FRB (the previous fixed values). However, ISO codes can now also be used. This setting can be overruled on workspace level.
