### ISSUE TITLE
Related Tables : provide support for 'Customer Templ.'

### ISSUE THREAD

**Issue by fvet** [BartPermentier/al-toolbox#67]
Following this [thread](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=8846299), it appears fields added to the 'Customer' table should be added to the 'Customer Templ.' table as well to fully benefit from the refactored customer template structure.

![image](https://user-images.githubusercontent.com/25268332/151924525-926c73af-38e1-4ff7-acdd-1313a1752570.png)

It would be good if the 'Contact/Customer/Vendor/Bank Account' group could be extended with the 'Customer Templ.' table, so devs won't forget to add new customer fields to the template table/pages as well.

**Comment by BartPermentier** [comment]
Done, thx!
