### ISSUE TITLE
Add round brackets everywhere in document

### ISSUE THREAD

**Issue by tscottjendev** [BartPermentier/al-toolbox#77]
Am I miss understanding the purpose of this quick fix?
It only seems to address one or two at a time not all the same issues or even for the same function.

See attached video.

https://user-images.githubusercontent.com/102963427/177492444-7dc3e4f7-9638-4f87-9f00-b434d8c09989.mp4

**Comment by BartPermentier** [comment]
It used to work, I'm guessing Microsoft f'd something up again. @dsaveyn if you have time to check

**Comment by dsaveyn** [comment]
Thank you for reporting this issue and our apologies for the delay. The solution will be available in the next release.
