### ISSUE TITLE
Surround with pragma in all documents not working

### ISSUE THREAD

**Issue by tscottjendev** [BartPermentier/al-toolbox#78]
I am trying to use the Surround ### with Pragma (in all documents) quick fix in my project (converting C/AL code).  It is not working.  It works for single instances but not in all documents. 
ALTB version 2.0.22

Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by dsaveyn** [comment]
Thank you for reporting this. The solution of this problem is included in the fix of #77. The solution will be available in the next release.
