### ISSUE TITLE
Disable some ALTB snippets?

### ISSUE THREAD

**Issue by fvet** [BartPermentier/al-toolbox#79]
I'd like to disable some snippets from ALTB using the 'Insert Snippet' command and then click the 'Hide' button.

![image](https://user-images.githubusercontent.com/25268332/191324881-2a987f28-533f-4ece-8be1-17137f015a2a.png)

However, none of the ALTB snippets are listed.

![image](https://user-images.githubusercontent.com/25268332/191324815-bc1a3368-434e-4c5c-a0c1-62410a721c85.png)

Can you verify if snippets could be listed here too?

**Comment by dsaveyn** [comment]
> @dsaveyn I think this is because our snippets are dynamic (atleast the ones with regions around them). I don't know if we can add some snippets the normal way?

@BartPermentier You're right. We are inserting the snippets using a SnippetCompletionItemProvider at runtime. Other extensions, for example CRS, specify the snippets in the package.json file like this:

![image](https://user-images.githubusercontent.com/92365904/206717207-de36f1c0-a601-4fc2-ae55-82ac37b67457.png)

We could adjust the ALTB snippets so they work in a similar way, but then we need to adjust the files at runtime to support our variable settings.

**Comment by BartPermentier** [comment]
If it's possible then do it ;)

**Comment by dsaveyn** [comment]
We reviewed this internally and we see some problems here: our snippets are dynamically generated and adjusted. For this we use a custom completion provider. One of the side effects of using this is that the snippets do not show up in the Snippets: Insert Snippet functionality. Only snippets files that are pre-defined are displayed there. Currently there's no way to easily solve this. We were thinking of generating the snippet files and writing them when loading the extension, but this requires some major rework and is not the cleanest solution. For now we will not tackle this.
