### ISSUE TITLE
Create Regions doesn't work with multiple apps in Workspace

### ISSUE THREAD

**Issue by achim-t** [BartPermentier/al-toolbox#88]
This only happens, when the app folder's name is part of another app folder.

![image](https://user-images.githubusercontent.com/11352910/195612418-cf89c274-6d33-4387-b15f-63a5cf81eab4.png)

Contents of the .al file:
![image](https://user-images.githubusercontent.com/11352910/195612499-cc355be5-9741-4a11-ae04-659d2e624814.png)

Creating regions works fine in app2 but doesn't work at all in app.

The message in Log (Window):
```
[2022-10-13 15:40:02.752] [renderer14] [error] Multiple app.json files found:
/c:/Users/achim-t/Documents/AL/ALProject33/app2/app.json, /c:/Users/achim-t/Documents/AL/ALProject33/app/app.json
```

If I rename app to app1, it works in both al files.

Other ALTB function are probably affected as well. For instance "Renumber AL objects" shows an error notification with the same "Multiple app.json files found" message.

**Comment by dsaveyn** [comment]
Thank you for reporting this issue and suggesting the solution. The solution will be available in the next release.
