### ISSUE TITLE
Renumber AL Objects Error

### ISSUE THREAD

**Issue by tscottjendev** [BartPermentier/al-toolbox#99]
For a bigger project (converted from C/AL) I have about 250 objects when I run `Renumber AL Objects` it I get
![image](https://user-images.githubusercontent.com/102963427/210553768-16d0f681-7881-4d4e-8506-36951ea70928.png)

For much smaller projects (<10 objects) the command works.

AL Toolbox Version: v2.0.25
VS Code:
Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

App.json
```
{
  "id": "5cf9b6f5-d7f5-4ff9-973a-3134e3b19716",
  "name": "Internal System",
  "publisher": "Jendev",
  "version": "20.1.0.1",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [
    {
      "id": "e6328152-bb29-4664-9dae-3bc7eaae1fd8",
      "name": "Email - Outlook REST API",
      "publisher": "Microsoft",
      "version": "20.1.39764.39901"
    }
  ],
  "screenshots": [],
  "platform": "1.0.0.0",
  "application": "20.1.0.0",
  "idRanges": [
    {
      "from": 50000,
      "to": 50999
    }
  ],
  "resourceExposurePolicy": {
    "allowDebugging": true,
    "allowDownloadingSource": false,
    "includeSourceInSymbolFile": false
  },
  "runtime": "9.0",
  "target": "Cloud",
  "features": ["NoImplicitWith"]
} 
```

Am I doing something wrong?

**Comment by BartPermentier** [comment]
No, I'm afraid it is a known issue. We haven't found a solution yet.

**Comment by dsaveyn** [comment]
Thank you for reporting this. Apparently vscode could not cope with opening multiple files at once. We've added a mechanism to compensate for this behavior. The fix will be included in the next release.

@BartPermentier
